### ISSUE TITLE
Doesn't seem to work for me on CE1.8

### ISSUE THREAD

**Issue by maxedout** [deved-it/SalguaMagentoAddProduct#1]
I am using the default onepage checkout with this url for testing

http://www.fakedomain.com/checkout/cart/add?product=850

i unfortunately get taken to an empty cart instead.

**Comment by salgua** [comment]
you must use

http://yourshop.com/urlcheckout/add?product=6&coupon_code=XXXXXX

you are using the default one...

**Comment by maxedout** [comment]
Ok, I had misunderstood urlcheckout to mean checkout URL (replace with actual). All clear now.

I am sure I cannot be the only one dense enough to not have read it properly.

This works great, thanks again.
