### ISSUE TITLE
Just a quck thanks

### ISSUE THREAD

**Issue by micwallace** [deved-it/SalguaMagentoAddProduct#10]
This is not an issue :-D

I just wanted to say thanks for creating this module.
It's been a great help, after hours trying to add this functionality myself I came across this and it just worked :+1: 
Keep up the great work.
Also I'd like to buy you a beer so put a donate button in the .md or maybe even add it to the magento connect store.

Cheers,
Michael

**Comment by salgua** [comment]
Thank you Michael!
